export type SubsystemCategory = 'AERO' | 'POWERTRAIN' | 'CHASSIS' | 'SUSPENSION'

export interface CarPartMetadata {
  id: string
  name: string
  category: SubsystemCategory
  subsystem: string
  material: string
  massKg: number
  dimensionsMm: string
  fiaArticle: string
  description: string
  keyFeatures: string[]
  meshName: string
}

export const F1_2026_CAR_PARTS: CarPartMetadata[] = [
  // ==========================================
  // 1. AERODYNAMICS & BODYWORK
  // ==========================================
  {
    id: 'front_wing_mainplane',
    name: 'Front Wing Mainplane & Inwash Endplates',
    category: 'AERO',
    subsystem: 'Front Aerodynamic Surface',
    material: 'High-Modulus Torayca T1000 Carbon Composite / Rohacell Core',
    massKg: 8.4,
    dimensionsMm: '1900 x 520 x 180',
    fiaArticle: 'FIA 2026 Art. 3.4 (Front Aerodynamic Surfaces)',
    description: 'Narrower 1900mm aerodynamic front wing base structure designed to channel front wheel wake inward toward the sidepod undercut rather than spilling outwash into the trailing wake.',
    keyFeatures: ['1900mm FIA-compliant total span', 'Integrated leading-edge inwash cascade', 'Aerodynamic vortex generators for floor feed'],
    meshName: 'part_front_wing_mainplane',
  },
  {
    id: 'front_wing_active_flaps',
    name: 'Dual-Element Active Front Wing Flaps',
    category: 'AERO',
    subsystem: 'Active Aerodynamics System (AAS)',
    material: 'Ultra-Stiff Prepreg Carbon Fiber / Titanium Pivot Hinges',
    massKg: 3.2,
    dimensionsMm: '860 x 140 x 30 (x2)',
    fiaArticle: 'FIA 2026 Art. 3.4.7 (Active Front Wing Flap Motion)',
    description: 'Electromechanically actuated dual front wing flap surfaces that articulate between Corner Mode (Z-Mode: High Downforce) and Straight Mode (X-Mode: Low Drag, -14° pitch shedding front aero load).',
    keyFeatures: ['Dual electro-hydraulic micro-actuators', 'Continuous angle trimming (-14° to +32°)', 'Automatic failsafe high-downforce default'],
    meshName: 'part_front_wing_active_flaps',
  },
  {
    id: 'front_wheel_deflectors',
    name: 'Front Wheel Wake Deflectors & Inwash Vanes',
    category: 'AERO',
    subsystem: 'Wheel Wake Management',
    material: 'Compression Molded Carbon-PEEK Composite',
    massKg: 1.8,
    dimensionsMm: '340 x 220 x 85 (x2)',
    fiaArticle: 'FIA 2026 Art. 3.5 (Front Wheel Deflectors)',
    description: 'Mandatory aerodynamic vertical deflectors mounted forward of the sidepod floor entry to control the high-energy tyre spray and direct turbulent air into cooling ducts.',
    keyFeatures: ['Integrated brake duct feed lip', 'Wake-shedding boundary layer control', 'High impact resistance against debris'],
    meshName: 'part_front_wheel_deflectors',
  },
  {
    id: 'underfloor_diffuser',
    name: 'Partially Flat Floor & Step Diffuser',
    category: 'AERO',
    subsystem: 'Underfloor Aerodynamic Assembly',
    material: 'Solid Carbon-Bismaleimide Honeycomb with Titanium Skid Blocks',
    massKg: 19.5,
    dimensionsMm: '2600 x 1450 x 110',
    fiaArticle: 'FIA 2026 Art. 3.6 (Underfloor & Diffuser Dimensions)',
    description: '1450mm wide stepped underfloor with reduced ground-effect Venturi tunnels and lower diffuser expansion ratio, eliminating violent high-speed porpoising while maintaining 45% floor downforce.',
    keyFeatures: ['1450mm floor width (-150mm vs 2025)', 'Machined Jabroc wood & titanium skid blocks', 'Low-sensitivity stepped floor entry plane'],
    meshName: 'part_underfloor_diffuser',
  },
  {
    id: 'sidepods_cooling_louvres',
    name: 'Sidepods with High-Undercut Inlets & Louvres',
    category: 'AERO',
    subsystem: 'Sidepod & Cooling Architecture',
    material: 'Autoclave Cured Carbon/Epoxy Thin-Wall Sandwich',
    massKg: 11.2,
    dimensionsMm: '1680 x 480 x 380 (x2)',
    fiaArticle: 'FIA 2026 Art. 3.7 (Bodywork Ahead of Rear Wheels)',
    description: 'Extreme undercut sidepod packaging housing canted radiators and intercoolers, feeding clean air over the floor upper surface toward the rear diffuser and rear wing.',
    keyFeatures: ['Dynamic cooling aperture louvre arrays', 'Aggressive lower undercut for vortex guidance', 'Internal composite crash structure integration'],
    meshName: 'part_sidepods_cooling_louvres',
  },
  {
    id: 'engine_cover_shark_fin',
    name: 'Engine Cover & Central Dorsal Stabilizer',
    category: 'AERO',
    subsystem: 'Upper Bodywork & Flow Conditioning',
    material: 'Aramid/Carbon Hybrid Ultra-Lightweight Shell',
    massKg: 6.8,
    dimensionsMm: '1850 x 620 x 40',
    fiaArticle: 'FIA 2026 Art. 3.8 (Engine Cover & Dorsal Fin)',
    description: 'Slim engine canopy incorporating the overhead air intake duct for turbocharger air feed, transitioning into a full-length dorsal fin providing high-yaw aerodynamic cornering stability.',
    keyFeatures: ['Direct turbo intake NACA duct', 'High-yaw crosswind stabilization fin', 'Quick-release quarter-turn fasteners'],
    meshName: 'part_engine_cover_shark_fin',
  },
  {
    id: 'rear_wing_3element_active',
    name: '3-Element Active Rear Wing & Actuator Pod',
    category: 'AERO',
    subsystem: 'Rear Aerodynamic Assembly',
    material: 'Ultra-High-Modulus Carbon Fiber / 7075-T6 Aerospace Aluminum Actuator',
    massKg: 10.5,
    dimensionsMm: '1080 x 420 x 360',
    fiaArticle: 'FIA 2026 Art. 3.9 (Rear Wing Assembly & Active Motion)',
    description: '3-element rear wing structure replacing traditional single-element DRS with full active aero articulation (+28° opening in Straight Mode, shedding 45% car drag) without lower beam wings.',
    keyFeatures: ['3-element high-lift camber profile', 'Integrated high-pressure electro-hydraulic pod', 'Simplified endplates compliant with 2026 low-wake rules'],
    meshName: 'part_rear_wing_3element_active',
  },

  // ==========================================
  // 2. POWERTRAIN & HYBRID ENERGY STORE
  // ==========================================
  {
    id: 'ice_16l_v6_turbo',
    name: '1.6L 90° V6 Turbocharged Internal Combustion Engine',
    category: 'POWERTRAIN',
    subsystem: 'Thermal Propulsion Unit',
    material: 'Cast Aluminum-Silicon Alloy Block / Forged Steel Crank / DLC Coated Valvetrain',
    massKg: 135.0,
    dimensionsMm: '580 x 510 x 460',
    fiaArticle: 'FIA 2026 Art. 5 (Power Unit Technical Regulations)',
    description: 'Direct-injected 1.6L 90° V6 ICE producing ~400 kW (535 bhp) at 15,000 RPM, powered exclusively by 100% advanced sustainable drop-in e-fuel under a 3,000 MJ/h energy flow limit.',
    keyFeatures: ['400 kW peak thermal power output', '100% sustainable advanced non-fossil e-fuel', 'Direct cylinder injection at 500 bar pressure'],
    meshName: 'part_ice_16l_v6_turbo',
  },
  {
    id: 'mguk_350kw_generator',
    name: '350 kW Crankshaft MGU-K Kinetic Motor Generator',
    category: 'POWERTRAIN',
    subsystem: 'Electrical Propulsion & Recovery',
    material: 'Permanent Magnet Synchronous AC Motor / Carbon Sleeved Rotor',
    massKg: 21.5,
    dimensionsMm: '240 x 210 x 190',
    fiaArticle: 'FIA 2026 Art. 5.2.2 (MGU-K Power & Recovery Limits)',
    description: 'Tripled-output 350 kW (470 bhp) electric motor generator coupled directly to the ICE crankshaft, recovering up to 8.5 MJ/lap under braking and delivering instant high-torque deployment.',
    keyFeatures: ['350 kW peak electrical power (tripled from 2025)', '8.5 MJ/lap braking regen capacity', 'Manual Override Mode full boost up to 337 km/h'],
    meshName: 'part_mguk_350kw_generator',
  },
  {
    id: 'turbocharger_wastegate',
    name: 'Single Turbocharger & Electronic Wastegate Actuator',
    category: 'POWERTRAIN',
    subsystem: 'Forced Induction System',
    material: 'Inconel 718 Turbine Wheel / Titanium Compressor Impeller',
    massKg: 12.0,
    dimensionsMm: '290 x 240 x 220',
    fiaArticle: 'FIA 2026 Art. 5.1.8 (Pressure Charging Regulations)',
    description: 'High-pressure single turbocharger mounted within the engine cylinder bank valley, operating up to 125,000 RPM with twin electronically modulated pneumatic wastegate valves.',
    keyFeatures: ['125,000 RPM maximum turbine rotation', 'Ceramic ball-bearing cartridge with oil cooling', 'Active anti-lag ignition mapping integration'],
    meshName: 'part_turbocharger_wastegate',
  },
  {
    id: 'exhaust_manifold_inconel',
    name: 'Equal-Length Inconel 718 Exhaust Manifold & Tailpipe',
    category: 'POWERTRAIN',
    subsystem: 'Exhaust Gas Expulsion',
    material: 'Hydraulic Formed 0.6mm Inconel 718 Alloy with Ceramic Heat Shield',
    massKg: 4.8,
    dimensionsMm: '620 x 440 x 280',
    fiaArticle: 'FIA 2026 Art. 5.8 (Exhaust System Dimensions & Acoustic Limits)',
    description: 'Tuned equal-length 6-into-1 Inconel exhaust headers converging into a single central tailpipe, delivering enhanced acoustic resonance and optimized turbine pulse scavenging.',
    keyFeatures: ['0.6mm ultra-thin Inconel wall thickness', '1,050°C thermal tolerance with gold foil insulation', 'Optimized acoustic resonance profile for pure engine note'],
    meshName: 'part_exhaust_manifold_inconel',
  },
  {
    id: 'energy_store_800v_battery',
    name: '800V Lithium-NMC Energy Store Battery Enclosure',
    category: 'POWERTRAIN',
    subsystem: 'High-Voltage Energy Storage',
    material: 'Carbon-Kevlar Armored Enclosure / Cylindrical Lithium-NMC Cells',
    massKg: 35.0,
    dimensionsMm: '720 x 360 x 140',
    fiaArticle: 'FIA 2026 Art. 5.3 (Energy Store Safety & Capacity)',
    description: 'Nominal 800V DC high-capacity Lithium-NMC battery pack positioned low inside the monocoque survival cell beneath the fuel tank for optimal center of gravity and safety.',
    keyFeatures: ['4.0 MJ active storage buffer capacity', 'Dielectric immersion fluid cooling system', 'FIA-certified ballistic carbon-aramid casing'],
    meshName: 'part_energy_store_800v_battery',
  },
  {
    id: 'power_electronics_inverter',
    name: 'Dual Silicon Carbide (SiC) Power Inverters',
    category: 'POWERTRAIN',
    subsystem: 'High-Voltage Power Conversion',
    material: 'Mil-Spec CNC Machined Magnesium Case / SiC MOSFET Substrates',
    massKg: 7.2,
    dimensionsMm: '310 x 220 x 95',
    fiaArticle: 'FIA 2026 Art. 5.4 (Power Control Units & Voltage Limits)',
    description: 'High-efficiency Silicon Carbide (SiC) power inverters switching at 40 kHz with 99.1% electrical efficiency to manage the 350 kW bidirectional energy flow to the MGU-K.',
    keyFeatures: ['99.1% power conversion efficiency', '40 kHz switching frequency with low harmonic loss', 'Integrated CAN-FD and telemetry transceiver'],
    meshName: 'part_power_electronics_inverter',
  },
  {
    id: 'gearbox_8speed_seamless',
    name: '8-Speed Seamless Sequential Carbon Gearbox Casing',
    category: 'POWERTRAIN',
    subsystem: 'Transmission & Drivetrain',
    material: 'Structural Carbon Fiber Composite Main Case / Maraging Steel Gears',
    massKg: 28.5,
    dimensionsMm: '480 x 340 x 320',
    fiaArticle: 'FIA 2026 Art. 7 (Transmission & Gear Ratios)',
    description: 'Longitudinally mounted 8-speed sequential seamless-shift transmission housed inside a carbon fiber structural casing that forms the rear suspension mounting anchor points.',
    keyFeatures: ['Zero-torque-loss seamless shift mechanism (<2ms)', 'Integrated rear suspension pickup hardpoints', 'Hydraulic multi-plate limited slip differential'],
    meshName: 'part_gearbox_8speed_seamless',
  },

  // ==========================================
  // 3. CHASSIS, COCKPIT & DRIVER SAFETY
  // ==========================================
  {
    id: 'monocoque_survival_tub',
    name: 'Carbon-Honeycomb Composite Monocoque Survival Tub',
    category: 'CHASSIS',
    subsystem: 'Chassis Core Safety Cell',
    material: 'Intermediate Modulus Carbon Fiber / Aluminum Honeycomb Sandwich',
    massKg: 62.0,
    dimensionsMm: '2450 x 680 x 590',
    fiaArticle: 'FIA 2026 Art. 12 & 13 (Survival Cell & Structural Tests)',
    description: 'Ultra-rigid safety cell designed to withstand 50G impacts, tested to survive 300 kN static lateral crush loads while serving as the primary structural spine of the vehicle.',
    keyFeatures: ['300 kN static side load certification', 'Integrated driver extraction seat cavity', 'Internal 100-litre Kevlar fuel cell cavity'],
    meshName: 'part_monocoque_survival_tub',
  },
  {
    id: 'halo_safety_titanium',
    name: 'Grade 5 Titanium Halo & Carbon Aero Fairing',
    category: 'CHASSIS',
    subsystem: 'Cockpit Head Protection',
    material: 'Forged Grade 5 Ti-6Al-4V Titanium Structure with Carbon Outer Shell',
    massKg: 7.0,
    dimensionsMm: '820 x 640 x 280',
    fiaArticle: 'FIA 2026 Art. 12.4 (Secondary Roll Structure - Halo)',
    description: 'FIA standard cockpit protection hoop engineered to support a 125 kN vertical load (equivalent to the weight of two London double-decker buses) with integrated aero flow vanes.',
    keyFeatures: ['125 kN static vertical load capacity', 'Aerodynamic wake conditioning outer shell', 'Integrated cockpit LED status and marshaling light'],
    meshName: 'part_halo_safety_titanium',
  },
  {
    id: 'front_impact_structure_fis',
    name: 'Two-Stage Front Impact Structure (FIS) & Nose Cone',
    category: 'CHASSIS',
    subsystem: 'Frontal Crash Absorption',
    material: 'Progressive Crush Carbon-Dyneema Composite Matrix',
    massKg: 8.9,
    dimensionsMm: '880 x 360 x 290',
    fiaArticle: 'FIA 2026 Art. 13.3 (Front Impact Structure Regulations)',
    description: 'Two-stage progressive crash cone engineered to absorb 90 kJ of kinetic energy during head-on deceleration, designed to prevent nose shearing during secondary angled impacts.',
    keyFeatures: ['Two-stage progressive energy crush profile', 'Anti-detachment tether anchor system', 'Integrated high-speed pit camera housing'],
    meshName: 'part_front_impact_structure_fis',
  },
  {
    id: 'side_intrusion_panels_zylon',
    name: 'Side Impact Absorption Structures (SIAS) & Zylon Panels',
    category: 'CHASSIS',
    subsystem: 'Lateral Intrusion Protection',
    material: 'Multi-Axial Zylon Fibers / Carbon-Epoxy Laminate',
    massKg: 9.4,
    dimensionsMm: '1420 x 420 x 45 (x2)',
    fiaArticle: 'FIA 2026 Art. 13.5 (Side Intrusion Test Standards)',
    description: 'High-tensile Zylon anti-penetration sheets bonded across the monocoque flanks to stop sharp suspension wishbone penetration during T-bone lateral collisions.',
    keyFeatures: ['Zylon ballistic-grade fiber layup', 'Double crush-tube energy absorption spar', 'Complete lateral intrusion resistance'],
    meshName: 'part_side_intrusion_panels_zylon',
  },
  {
    id: 'rear_impact_structure_ris',
    name: 'Rear Impact Structure (RIS) & Endplate Rain LEDs',
    category: 'CHASSIS',
    subsystem: 'Rear Crash Absorption & Signaling',
    material: 'Crushable Carbon-Composite Cone / Ultra-Bright LED Arrays',
    massKg: 5.6,
    dimensionsMm: '480 x 240 x 210',
    fiaArticle: 'FIA 2026 Art. 13.6 & 14.3 (Rear Impact & Safety Lighting)',
    description: 'Rear carbon pyramid absorbing rearward shunts, mounting the FIA high-intensity flashing rain light (1500 cd) and dual vertical rear wing endplate safety LEDs.',
    keyFeatures: ['40 kJ rear crash absorption capacity', '1,500 candela high-visibility pulsing rain light', 'Dual vertical endplate safety status lights'],
    meshName: 'part_rear_impact_structure_ris',
  },
  {
    id: 'cockpit_seat_harness',
    name: 'Custom Molded Carbon Bead Seat & 6-Point Harness',
    category: 'CHASSIS',
    subsystem: 'Driver Ergonomics & Restraint',
    material: 'Polyurethane Resin Bead Core in Carbon Shell / Nomex Fireproof Cover',
    massKg: 3.8,
    dimensionsMm: '980 x 460 x 380',
    fiaArticle: 'FIA 2026 Art. 12.1 (Driver Cockpit Dimensions & Extraction)',
    description: 'Driver-specific molded vacuum bead seat equipped with rapid-extraction lift straps, 6-point quick-release harness, and integrated medical biometric monitoring links.',
    keyFeatures: ['Single-motion 6-point camlock buckle', 'Emergency extraction lift handles', 'Biometric telemetry pulse and oxygen sensor links'],
    meshName: 'part_cockpit_seat_harness',
  },
  {
    id: 'steering_wheel_oled_controls',
    name: '2026 Carbon Steering Wheel with OLED Telemetry',
    category: 'CHASSIS',
    subsystem: 'Driver Interface & Controls',
    material: 'CNC Machined Carbon Fiber / Anodized Aluminum Rotary Knobs',
    massKg: 1.35,
    dimensionsMm: '285 x 175 x 90',
    fiaArticle: 'FIA 2026 Art. 9.4 & 8.6 (Steering Wheel Display & Controls)',
    description: 'Formula 1 command interface featuring a 4.3" high-contrast OLED telemetry screen, 12 tactile thumb rotaries, magnetic shift paddles, and dedicated Active Aero / Overtake Mode buttons.',
    keyFeatures: ['4.3-inch anti-glare OLED instrumentation screen', 'Thumb-actuated Active Aero Mode toggle (Z/X)', 'Dual progressive clutch paddles and magnetic shifters'],
    meshName: 'part_steering_wheel_oled_controls',
  },

  // ==========================================
  // 4. SUSPENSION, BRAKES & RUNNING GEAR
  // ==========================================
  {
    id: 'front_suspension_wishbones',
    name: 'Front Double Wishbone & Push-Rod Dampers',
    category: 'SUSPENSION',
    subsystem: 'Front Kinematics & Damping',
    material: 'Aero-Profiled Carbon Wishbones / Titanium Flexures / Inboard Torsion Bars',
    massKg: 14.8,
    dimensionsMm: '840 x 560 x 320 (x2)',
    fiaArticle: 'FIA 2026 Art. 10.1 (Front Suspension & Wishbone Fairings)',
    description: 'Aerodynamically shaped double wishbone suspension with push-rod actuated inboard heave dampers, third elements, and adjustable anti-roll bar (ARB) for precise ride-height control.',
    keyFeatures: ['Inboard torsion bar and hydraulic heave spring', 'Aerodynamic teardrop carbon shroud profiles', 'Adjustable front anti-roll bar (ARB) mechanism'],
    meshName: 'part_front_suspension_wishbones',
  },
  {
    id: 'rear_suspension_multilink',
    name: 'Rear Multi-Link Suspension with Torsion Bars',
    category: 'SUSPENSION',
    subsystem: 'Rear Kinematics & Traction',
    material: 'Carbon Composite Links / Nickel-Chromium Steel Uprights',
    massKg: 16.2,
    dimensionsMm: '860 x 580 x 340 (x2)',
    fiaArticle: 'FIA 2026 Art. 10.2 (Rear Suspension & Gearbox Mounts)',
    description: 'Multi-link rear suspension geometry mounted directly into the gearbox casing, engineered to maintain consistent tyre contact patch camber during high-lateral cornering.',
    keyFeatures: ['Anti-squat and anti-lift kinematics geometry', 'Direct carbon gearbox case mounting studs', 'Inboard rotary damper damping control'],
    meshName: 'part_rear_suspension_multilink',
  },
  {
    id: 'bbs_18inch_forged_wheels',
    name: '18-Inch Forged Magnesium BBS Rims & Aero Covers',
    category: 'SUSPENSION',
    subsystem: 'Wheel Assemblies',
    material: 'Forged AZ80 Magnesium Alloy / Carbon Fiber Aero Wheel Covers',
    massKg: 9.8,
    dimensionsMm: '457.2 x 280 (Front) / 457.2 x 375 (Rear)',
    fiaArticle: 'FIA 2026 Art. 11.2 (Wheel Rims & Spec Dimensions)',
    description: 'Lightweight 18-inch forged magnesium rims fitted with standardized carbon aerodynamic wheel covers designed to eliminate rim turbulence and optimize brake heat dissipation.',
    keyFeatures: ['Single central locking nut with safety retention pin', 'Carbon fiber flush aero wheel covers', 'Internal anti-slip bead knurling for torque transfer'],
    meshName: 'part_bbs_18inch_forged_wheels',
  },
  {
    id: 'pirelli_2026_spec_tyres',
    name: '2026 Specification Pirelli Tyres (280mm F / 375mm R)',
    category: 'SUSPENSION',
    subsystem: 'Pneumatic Tyres & Contact Patch',
    material: 'Synthetic Polybutadiene Rubber Compounds / Rayon Carcass',
    massKg: 9.6,
    dimensionsMm: 'Ø705 x 280 (Front) / Ø705 x 375 (Rear)',
    fiaArticle: 'FIA 2026 Art. 11.1 (Tyre Dimensions & Compounds)',
    description: 'Narrower 2026 specification slick tyres (280mm front, 375mm rear) engineered with reduced rolling resistance and revised thermal operating windows (85°C–115°C).',
    keyFeatures: ['280mm front width (-25mm vs 2025)', '375mm rear width (-30mm vs 2025)', 'Two-layer thermal tread and carcass chemistry'],
    meshName: 'part_pirelli_2026_spec_tyres',
  },
  {
    id: 'carbon_carbon_brake_system',
    name: 'Carbon-Carbon Brake Discs & 6-Piston Calipers',
    category: 'SUSPENSION',
    subsystem: 'Friction Braking System',
    material: '3D Continuous Carbon-Carbon Matrix / Monobloc Lithium-Aluminum Calipers',
    massKg: 13.6,
    dimensionsMm: 'Ø328 x 32 (Front) / Ø280 x 28 (Rear)',
    fiaArticle: 'FIA 2026 Art. 11.3 (Braking Systems & Cooling Inlets)',
    description: 'High-temperature carbon-carbon brake discs capable of withstanding 1,200°C peak braking temperatures with 1,400 miniature cooling ventilation holes per disc.',
    keyFeatures: ['1,400 laser-drilled cooling ventilation holes', '6-piston monobloc lithium-aluminum calipers', '1,200°C maximum thermal operating threshold'],
    meshName: 'part_carbon_carbon_brake_system',
  },
  {
    id: 'brake_by_wire_bbw_actuator',
    name: 'Rear Electronic Brake-by-Wire (BBW) Hydraulic Actuator',
    category: 'SUSPENSION',
    subsystem: 'Brake Torque Blending & Control',
    material: 'Aerospace Grade 7075 Aluminum / High-Speed Servo Solenoids',
    massKg: 2.9,
    dimensionsMm: '190 x 140 x 110',
    fiaArticle: 'FIA 2026 Art. 11.4 (Brake-by-Wire & Rear Brake Control)',
    description: 'High-frequency electronic brake-by-wire hydraulic unit blending mechanical rear friction braking with the 350 kW MGU-K regenerative braking torque seamlessly in <3ms.',
    keyFeatures: ['<3 millisecond hydraulic response latency', 'Seamless MGU-K regen and friction torque blending', 'Triple-redundant hydraulic backup circuit'],
    meshName: 'part_brake_by_wire_bbw_actuator',
  },
  {
    id: 'aero_rake_pitot_rig',
    name: '3D Pitot-Tube Kiel Probe Aero-Rake Grid Array',
    category: 'AERO',
    subsystem: 'Boundary Layer Aerodynamic Instrumentation',
    material: 'Grade 5 Titanium Tubular Lattice / Carbon Fiber Mounts / Multi-Port Kiel Probes',
    massKg: 4.2,
    dimensionsMm: '420 x 360 x 180 (x2 Arrays)',
    fiaArticle: 'FIA 2026 Art. 3.4 & 3.5 (Aerodynamic Testing & Pressure Instrumentation)',
    description: 'Precision aerodynamic boundary layer measurement rig mounted directly behind the front tyres. Dual 4x5 Kiel probe matrix arrays map front wheel wake turbulence, boundary layer vorticity, and total pressure loss (Pt/P0) at 100 Hz.',
    keyFeatures: ['Dual 4x5 Kiel probe matrix (40 dynamic pressure transducers)', 'True total-pressure recovery insensitive to ±30° yaw', 'Real-time 3D boundary layer wake gradient mapping'],
    meshName: 'part_aero_rake_pitot_rig',
  },
]

