export type WheelControlCategory =
  | 'AERO'
  | 'POWERTRAIN'
  | 'BRAKES'
  | 'TRANSMISSION'
  | 'RADIO'
  | 'SAFETY'
  | 'TELEMETRY'
  | 'DRIVER_COMFORT'

export type WheelControlType =
  | 'PUSH_BUTTON'
  | 'ROTARY_DIAL'
  | 'THUMB_ROTARY'
  | 'PADDLE_SHIFTER'
  | 'CLUTCH_PADDLE'
  | 'DISPLAY_SCREEN'
  | 'LED_ARRAY'

export interface WheelControlMetadata {
  id: string
  name: string
  acronym: string
  type: WheelControlType
  category: WheelControlCategory
  color: string
  accentColor?: string
  positionLabel: string
  description: string
  fiaContext: string
  physicsImpact: string
  actionHint: string
  defaultValue?: number | string
  options?: { value: string | number; label: string; description?: string }[]
  min?: number
  max?: number
  step?: number
  unit?: string
  sound: 'button' | 'rotary' | 'paddle_up' | 'paddle_down' | 'beep' | 'radio'
}

export const F1_STEERING_WHEEL_CONTROLS: WheelControlMetadata[] = [
  // ==========================================
  // TOP ROW & THUMB PUSH BUTTONS
  // ==========================================
  {
    id: 'btn_drs',
    name: 'DRS & Active Aero Override',
    acronym: 'DRS',
    type: 'PUSH_BUTTON',
    category: 'AERO',
    color: '#00ff66',
    positionLabel: 'Top Left Thumb',
    description: 'Activates low-drag straight-line aerodynamic mode and 2026 active aerodynamics override.',
    fiaContext: 'FIA Technical Reg 3.10 — Active aerodynamic device permissible on designated DRS zones and overtaking zones.',
    physicsImpact: 'Reduces rear wing drag by 38% and increases top speed by up to 18 km/h on straights.',
    actionHint: 'Click to toggle Straight-Line Low Drag mode',
    sound: 'button',
  },
  {
    id: 'btn_radio',
    name: 'Team Radio Communication',
    acronym: 'RADIO',
    type: 'PUSH_BUTTON',
    category: 'RADIO',
    color: '#ffd000',
    positionLabel: 'Top Left Upper',
    description: 'Opens bi-directional encrypted audio channel with Race Engineer and Pit Wall.',
    fiaContext: 'FIA Sporting Reg 21 — Direct driver-to-pit radio communication channel monitoring telemetry and race control.',
    physicsImpact: 'Requests tactical updates, pit stop confirmation, and weather forecasts from race engineers.',
    actionHint: 'Click to key radio microphone and request pit wall telemetry update',
    sound: 'radio',
  },
  {
    id: 'btn_pit_limiter',
    name: 'Pit Lane Speed Limiter',
    acronym: 'PL',
    type: 'PUSH_BUTTON',
    category: 'SAFETY',
    color: '#ff2a2a',
    positionLabel: 'Top Right Upper',
    description: 'Enforces strictly governed 80 km/h (or 60 km/h) pit lane speed limit and flashes indicator LEDs.',
    fiaContext: 'FIA Sporting Reg 34.7 — Mandatory pit lane speed limiter to prevent severe sporting penalties and ensure pit crew safety.',
    physicsImpact: 'Hard ECU engine cut capping vehicle velocity at precisely 80.0 km/h regardless of throttle input.',
    actionHint: 'Click to arm / disarm 80 km/h pit lane limiter & send box confirmation',
    sound: 'beep',
  },
  {
    id: 'btn_overtake',
    name: 'ERS Overtake / Push-to-Pass',
    acronym: 'OT',
    type: 'PUSH_BUTTON',
    category: 'POWERTRAIN',
    color: '#b026ff',
    positionLabel: 'Top Right Thumb',
    description: 'Channels maximum permissible 350 kW MGU-K electrical boost for offensive overtaking or defensive moves.',
    fiaContext: 'FIA 2026 PU Regs — Electric powertrain override delivering maximum state-of-charge discharge.',
    physicsImpact: 'Unleashes instantaneous +350 kW electric torque directly to the rear axle.',
    actionHint: 'Click to engage max electrical energy discharge',
    sound: 'button',
  },
  {
    id: 'btn_soc_harvest',
    name: 'State of Charge Harvest (Recharge)',
    acronym: 'SOC',
    type: 'PUSH_BUTTON',
    category: 'POWERTRAIN',
    color: '#00e5ff',
    positionLabel: 'Middle Left',
    description: 'Forces high-efficiency MGU-K kinetic regenerative braking to rapidly replenish high-voltage battery cells.',
    fiaContext: 'Energy management protocol allowing driver to aggressively recover megajoules before critical overtake attempts.',
    physicsImpact: 'Increases regenerative drag under deceleration, boosting battery charging rate by +45%.',
    actionHint: 'Click to switch ERS into forced harvest mode',
    sound: 'button',
  },
  {
    id: 'btn_neutral',
    name: 'Gearbox Neutral Disconnect',
    acronym: 'N',
    type: 'PUSH_BUTTON',
    category: 'TRANSMISSION',
    color: '#00cc44',
    positionLabel: 'Upper Left Bezel',
    description: 'Disengages seamless-shift sequential transmission clutches into neutral gear.',
    fiaContext: 'Mandatory neutral position required for stationary pit stops and trackside marshaling safety.',
    physicsImpact: 'Decouples powertrain from rear driveshafts, idling engine revs.',
    actionHint: 'Click to drop gearbox into Neutral (N)',
    sound: 'button',
  },
  {
    id: 'btn_reverse',
    name: 'Reverse Gear Engagement',
    acronym: 'R',
    type: 'PUSH_BUTTON',
    category: 'TRANSMISSION',
    color: '#ff9900',
    positionLabel: 'Upper Right Bezel',
    description: 'Engages reverse gear with electronic interlock guard to recover from spin-outs or run-off traps.',
    fiaContext: 'FIA Technical Reg 9.2 — Transmission must include functional reverse gear operable by the driver.',
    physicsImpact: 'Reverses differential drive direction at low speed.',
    actionHint: 'Click to select Reverse Gear (R)',
    sound: 'button',
  },
  {
    id: 'btn_marshal_ack',
    name: 'Race Control Marshal Acknowledge',
    acronym: 'ACK',
    type: 'PUSH_BUTTON',
    category: 'SAFETY',
    color: '#f0f0f0',
    positionLabel: 'Center Upper',
    description: 'Acknowledges race director warning banners, safety car notices, and blue flag marshal warnings on LCD.',
    fiaContext: 'FIA Sporting Regs — Drivers must acknowledge race control directives within 5 seconds of telemetry notification.',
    physicsImpact: 'Dismisses active race control alert HUD banner from steering display.',
    actionHint: 'Click to acknowledge race control flags / messages',
    sound: 'button',
  },
  {
    id: 'btn_drink',
    name: 'Driver Hydration Pump',
    acronym: 'DRINK',
    type: 'PUSH_BUTTON',
    category: 'DRIVER_COMFORT',
    color: '#0088ff',
    positionLabel: 'Lower Left',
    description: 'Activates high-pressure electric peristaltic pump injecting electrolyte solution directly into helmet valve.',
    fiaContext: 'Cockpit driver survival equipment designed for extreme heat races (Qatar, Singapore, Bahrain).',
    physicsImpact: 'Prevents driver dehydration fatigue, stabilizing reaction times during long stints.',
    actionHint: 'Click to squirt electrolyte hydration pump',
    sound: 'button',
  },
  {
    id: 'btn_pass_pace',
    name: 'Attack Pace Mode (PASS)',
    acronym: 'PASS',
    type: 'PUSH_BUTTON',
    category: 'POWERTRAIN',
    color: '#ff5500',
    positionLabel: 'Lower Right',
    description: 'Immediately commands vehicle engine map and driver target delta into maximum attack pace.',
    fiaContext: 'Pit wall strategic pace instruction trigger.',
    physicsImpact: 'Increases engine power limit and pushes lap pace targets by -0.4s per lap at cost of tire degradation.',
    actionHint: 'Click to switch driver pace mode to Maximum Attack',
    sound: 'button',
  },
  {
    id: 'btn_bb_plus',
    name: 'Brake Balance Forward (+0.5%)',
    acronym: 'BB +',
    type: 'PUSH_BUTTON',
    category: 'BRAKES',
    color: '#ff3366',
    positionLabel: 'Right Thumb Upper',
    description: 'Shifts hydraulic brake pressure distribution forward toward the front carbon-carbon discs.',
    fiaContext: 'Brake-by-Wire (BBW) balance adjustment allowed within driver cockpit controls.',
    physicsImpact: 'Increases front braking stability, reduces rear lockups, but increases front tire graining.',
    actionHint: 'Click to shift brake balance +0.5% forward',
    sound: 'button',
  },
  {
    id: 'btn_bb_minus',
    name: 'Brake Balance Rearward (-0.5%)',
    acronym: 'BB -',
    type: 'PUSH_BUTTON',
    category: 'BRAKES',
    color: '#ff3366',
    positionLabel: 'Right Thumb Lower',
    description: 'Shifts hydraulic brake pressure distribution rearward toward the rear MGU-K regenerative system.',
    fiaContext: 'Brake-by-Wire (BBW) balance adjustment allowed within driver cockpit controls.',
    physicsImpact: 'Improves corner entry rotation, but increases rear tire slip under heavy braking.',
    actionHint: 'Click to shift brake balance -0.5% rearward',
    sound: 'button',
  },
  {
    id: 'btn_eb_plus',
    name: 'Engine Braking Increase (+)',
    acronym: 'EB +',
    type: 'PUSH_BUTTON',
    category: 'BRAKES',
    color: '#3388ff',
    positionLabel: 'Left Thumb Upper',
    description: 'Increases ICE engine throttle overrun resistance and MGU-K drag on corner deceleration.',
    fiaContext: 'Powertrain throttle overrun calibration.',
    physicsImpact: 'Provides sharper turn-in stability on corner entry with stronger engine decel.',
    actionHint: 'Click to increase engine braking level',
    sound: 'button',
  },
  {
    id: 'btn_eb_minus',
    name: 'Engine Braking Decrease (-)',
    acronym: 'EB -',
    type: 'PUSH_BUTTON',
    category: 'BRAKES',
    color: '#3388ff',
    positionLabel: 'Left Thumb Lower',
    description: 'Decreases engine overrun resistance, allowing smoother coasting and higher minimum corner speed.',
    fiaContext: 'Powertrain throttle overrun calibration.',
    physicsImpact: 'Reduces rear tire locking during trail braking in high-speed flowing corners.',
    actionHint: 'Click to decrease engine braking level',
    sound: 'button',
  },
  {
    id: 'btn_page_next',
    name: 'LCD Dashboard Page Next',
    acronym: 'PAGE +',
    type: 'PUSH_BUTTON',
    category: 'TELEMETRY',
    color: '#ffffff',
    positionLabel: 'Center Left Bezel',
    description: 'Cycles active display page on the central 4.3" FIA-spec LCD screen.',
    fiaContext: 'Multi-screen telemetry display protocol.',
    physicsImpact: 'Toggles between Race Telemetry, Tire Thermals, ERS Energy Flow, and Aerodynamics view.',
    actionHint: 'Click to cycle to next LCD telemetry page',
    sound: 'button',
  },
  {
    id: 'btn_page_prev',
    name: 'LCD Dashboard Page Prev',
    acronym: 'PAGE -',
    type: 'PUSH_BUTTON',
    category: 'TELEMETRY',
    color: '#ffffff',
    positionLabel: 'Center Right Bezel',
    description: 'Cycles to previous display page on the central 4.3" FIA-spec LCD screen.',
    fiaContext: 'Multi-screen telemetry display protocol.',
    physicsImpact: 'Toggles display pages backward.',
    actionHint: 'Click to cycle to previous LCD telemetry page',
    sound: 'button',
  },

  // ==========================================
  // ROTARY DIALS & THUMB WHEELS
  // ==========================================
  {
    id: 'rot_diff_entry',
    name: 'Differential Corner Entry Rotary',
    acronym: 'DIFF IN',
    type: 'THUMB_ROTARY',
    category: 'TRANSMISSION',
    color: '#ffcc00',
    positionLabel: 'Left Grip Thumb Wheel',
    description: 'Calibrates multi-plate limited slip differential lockup percentage under turn-in braking.',
    fiaContext: 'Electro-hydraulic differential ramp angle control.',
    physicsImpact: 'High value (65%) stabilizes braking in straight line; low value (48%) frees car for high-speed turn-in agility.',
    actionHint: 'Turn or click to adjust Differential Entry locking (45% - 70%)',
    defaultValue: 54,
    min: 45,
    max: 70,
    step: 1,
    unit: '%',
    sound: 'rotary',
  },
  {
    id: 'rot_diff_exit',
    name: 'Differential Corner Exit Rotary',
    acronym: 'DIFF OUT',
    type: 'THUMB_ROTARY',
    category: 'TRANSMISSION',
    color: '#ff9900',
    positionLabel: 'Right Grip Thumb Wheel',
    description: 'Calibrates multi-plate limited slip differential lockup under corner exit throttle application.',
    fiaContext: 'Electro-hydraulic differential power ramp control.',
    physicsImpact: 'High lockup delivers symmetric traction out of slow hairpins; lower lockup prevents snap oversteer on bumpy curbs.',
    actionHint: 'Turn or click to adjust Differential Exit locking (40% - 65%)',
    defaultValue: 58,
    min: 40,
    max: 65,
    step: 1,
    unit: '%',
    sound: 'rotary',
  },
  {
    id: 'rot_strat_mode',
    name: 'Engine Strategy Rotary (STRAT)',
    acronym: 'STRAT',
    type: 'ROTARY_DIAL',
    category: 'POWERTRAIN',
    color: '#e60000',
    positionLabel: 'Lower Center Rotary #1',
    description: 'Master 10-position rotary dial controlling ICE fuel mixture, turbo boost maps, and MGU-H/K deployment profiles.',
    fiaContext: 'Engine management mode selector permissible under FIA PU homologation regulations.',
    physicsImpact: 'Directly dictates engine output (750 kW to 850 kW peak) and fuel consumption rate (kg/lap).',
    actionHint: 'Click to cycle Strategy Modes (Strat 1 Quali -> Strat 2 Attack -> Strat 3 Race -> Strat 5 Fuel Save -> Strat 7 Wet -> Strat 10 Safety Car)',
    defaultValue: 3,
    options: [
      { value: 1, label: 'STRAT 1', description: 'Qualifying Hot Lap (100% Maximum ICE & MGU-K deploy)' },
      { value: 2, label: 'STRAT 2', description: 'Overtake / Attack Stint (Aggressive power delivery)' },
      { value: 3, label: 'STRAT 3', description: 'Standard Grand Prix Race Pace (Balanced tire & engine life)' },
      { value: 4, label: 'STRAT 4', description: 'High Degradation Management (Smooth torque curves)' },
      { value: 5, label: 'STRAT 5', description: 'Extreme Fuel & Lift-and-Coast Economy Stint' },
      { value: 7, label: 'STRAT 7', description: 'Wet Track Low Slip / Soft Throttle Map' },
      { value: 10, label: 'STRAT 10', description: 'Safety Car / Formation Lap Energy Conservation' },
    ],
    sound: 'rotary',
  },
  {
    id: 'rot_tire_selector',
    name: 'Tire Compound Calibration Rotary',
    acronym: 'TYRE',
    type: 'ROTARY_DIAL',
    category: 'TELEMETRY',
    color: '#ffffff',
    positionLabel: 'Lower Center Rotary #2',
    description: 'Calibrates ECU slip thresholds, rolling circumference, and thermal modeling for current tire compound.',
    fiaContext: 'FIA tire homologation sensor mapping.',
    physicsImpact: 'Informs traction control slip maps and thermal modeling of exact tire compound characteristics.',
    actionHint: 'Click to cycle compound setting (Soft, Medium, Hard, Intermediate, Wet)',
    defaultValue: 'MED',
    options: [
      { value: 'SOFT', label: 'SOFT (C5/C4)', description: 'Maximum grip, fast warm-up, high degradation' },
      { value: 'MED', label: 'MEDIUM (C3)', description: 'Balanced Grand Prix compound' },
      { value: 'HARD', label: 'HARD (C1/C2)', description: 'High durability, low thermal degradation' },
      { value: 'INTER', label: 'INTERMEDIATE', description: 'Damp track with intermediate grooved tread' },
      { value: 'WET', label: 'FULL WET', description: 'Standing water with high dispersion tread' },
    ],
    sound: 'rotary',
  },
  {
    id: 'rot_multifunction',
    name: 'Multi-Function Systems Rotary (MF)',
    acronym: 'MF-SYS',
    type: 'ROTARY_DIAL',
    category: 'TELEMETRY',
    color: '#00ccff',
    positionLabel: 'Lower Center Rotary #3',
    description: 'Multi-function rotary dial accessing sub-system diagnostics, brake shape migration, and telemetry logging.',
    fiaContext: 'Cockpit diagnostic bus selector.',
    physicsImpact: 'Allows deep fine-tuning of brake migration, torque delivery curves, and sensor calibrations.',
    actionHint: 'Click to cycle MF diagnostic subsystem pages',
    defaultValue: 1,
    options: [
      { value: 1, label: 'MF 1: SENSORS', description: 'Aero load & tire sensor telemetry' },
      { value: 2, label: 'MF 2: BRAKE SHAPE', description: 'High-speed vs low-speed brake migration' },
      { value: 3, label: 'MF 3: CLUTCH CAL', description: 'Bite-point calibration routine' },
      { value: 4, label: 'MF 4: HYDRAULICS', description: 'Valve pressure & steering rack feedback' },
    ],
    sound: 'rotary',
  },
  {
    id: 'rot_bite_point',
    name: 'Clutch Bite Point Offset Rotary',
    acronym: 'CLUTCH',
    type: 'ROTARY_DIAL',
    category: 'TRANSMISSION',
    color: '#bb00ff',
    positionLabel: 'Lower Center Rotary #4',
    description: 'Fine-tunes the launch clutch slip engagement point for perfect standing race starts without wheelspin.',
    fiaContext: 'FIA Technical Reg 9.3 — Manual clutch bite point control during standing starts.',
    physicsImpact: 'Optimizes 0-100 km/h standing start launch acceleration by minimizing tire slip.',
    actionHint: 'Turn or click to adjust clutch bite point percentage (15% - 85%)',
    defaultValue: 48,
    min: 15,
    max: 85,
    step: 1,
    unit: '%',
    sound: 'rotary',
  },

  // ==========================================
  // REAR PADDLE SHIFTERS & CLUTCHES
  // ==========================================
  {
    id: 'paddle_upshift',
    name: 'Carbon Fiber Upshift Paddle (+)',
    acronym: 'SHIFT UP',
    type: 'PADDLE_SHIFTER',
    category: 'TRANSMISSION',
    color: '#33ff33',
    positionLabel: 'Rear Right Paddle',
    description: 'Magnetic snap-action carbon fiber paddle shifter triggering instantaneous seamless upshifts (1 -> 8).',
    fiaContext: 'FIA Technical Reg 9.1 — Single-action mechanical paddle transmission actuator.',
    physicsImpact: 'Shifts up in under 0.005 seconds with zero torque interruption to the rear wheels.',
    actionHint: 'Click to pull paddle and shift UP a gear',
    sound: 'paddle_up',
  },
  {
    id: 'paddle_downshift',
    name: 'Carbon Fiber Downshift Paddle (-)',
    acronym: 'SHIFT DOWN',
    type: 'PADDLE_SHIFTER',
    category: 'TRANSMISSION',
    color: '#ff3333',
    positionLabel: 'Rear Left Paddle',
    description: 'Magnetic snap-action carbon paddle triggering rapid rev-matched downshifts into braking zones (8 -> 1).',
    fiaContext: 'FIA Technical Reg 9.1 — Paddle shift mechanism with electronic engine rev-matching.',
    physicsImpact: 'Shifts down with automatic throttle blip to prevent rear axle lockup on turn-in.',
    actionHint: 'Click to pull paddle and shift DOWN a gear',
    sound: 'paddle_down',
  },
  {
    id: 'paddle_clutch_left',
    name: 'Left Analog Launch Clutch Paddle',
    acronym: 'CLUTCH L',
    type: 'CLUTCH_PADDLE',
    category: 'TRANSMISSION',
    color: '#00ffff',
    positionLabel: 'Rear Lower Left',
    description: 'Progressive analog hall-effect clutch paddle for race start modulation.',
    fiaContext: 'FIA 2026 Standing Start Regulations — Single clutch paddle release mandated at lights out.',
    physicsImpact: 'Modulates clutch pressure plate clamping load from 0% to 100%.',
    actionHint: 'Click to pull launch clutch',
    sound: 'paddle_down',
  },
  {
    id: 'paddle_clutch_right',
    name: 'Right Analog Launch Clutch Paddle',
    acronym: 'CLUTCH R',
    type: 'CLUTCH_PADDLE',
    category: 'TRANSMISSION',
    color: '#00ffff',
    positionLabel: 'Rear Lower Right',
    description: 'Secondary analog clutch paddle used for dual-stage start launches.',
    fiaContext: 'FIA Start Line Procedure.',
    physicsImpact: 'Holds clutch exactly at calibrated bite point until launch release.',
    actionHint: 'Click to pull launch clutch',
    sound: 'paddle_up',
  },

  // ==========================================
  // DISPLAY & LEDS
  // ==========================================
  {
    id: 'disp_lcd_43',
    name: '4.3" High-Definition FIA LCD Display (PCF)',
    acronym: 'LCD DDU',
    type: 'DISPLAY_SCREEN',
    category: 'TELEMETRY',
    color: '#00f0ff',
    positionLabel: 'Center Upper Display',
    description: 'Ultra-bright sunlight-readable OLED display rendering live gear, speed, RPM, delta, ERS, and tire telemetry.',
    fiaContext: 'Standardized Display Driver Unit (DDU / PCF) mandated across all Formula 1 constructors.',
    physicsImpact: 'Direct real-time readout of 100 Hz simulation state, tire temps, brake temps, lap delta, and fuel.',
    actionHint: 'Click anywhere on LCD to switch telemetry pages (Race, Tires, ERS, Aero)',
    sound: 'button',
  },
  {
    id: 'led_shift_array',
    name: '15x High-Intensity RGB Shift LED Array',
    acronym: 'SHIFT LEDS',
    type: 'LED_ARRAY',
    category: 'TELEMETRY',
    color: '#ff0033',
    positionLabel: 'Top Display Brow',
    description: 'Progressive shift light array (5 Green -> 5 Red -> 5 Blue) indicating optimal gear shift point.',
    fiaContext: 'FIA shift indicator protocol synchronized with ECU rev-limiter.',
    physicsImpact: 'Provides visual cues for 12,500 - 15,000 RPM peak power upshift points.',
    actionHint: 'Flashes in real-time as engine reaches shift threshold',
    sound: 'beep',
  },
  {
    id: 'led_flag_left',
    name: 'Left FIA Flag Status LED Strip',
    acronym: 'FLAG L',
    type: 'LED_ARRAY',
    category: 'SAFETY',
    color: '#ffff00',
    positionLabel: 'Left Screen Bezel',
    description: '3x RGB LEDs displaying track status flags (Yellow, Green, Red, Blue, VSC, SC).',
    fiaContext: 'FIA in-cockpit electronic flag notification system.',
    physicsImpact: 'Alerts driver to immediate sector hazards and safety car speed delta requirements.',
    actionHint: 'Illuminates with active race control flag status',
    sound: 'beep',
  },
  {
    id: 'led_flag_right',
    name: 'Right FIA Flag Status LED Strip',
    acronym: 'FLAG R',
    type: 'LED_ARRAY',
    category: 'SAFETY',
    color: '#ffff00',
    positionLabel: 'Right Screen Bezel',
    description: '3x RGB LEDs displaying track status flags (Yellow, Green, Red, Blue, VSC, SC).',
    fiaContext: 'FIA in-cockpit electronic flag notification system.',
    physicsImpact: 'Alerts driver to immediate sector hazards and safety car speed delta requirements.',
    actionHint: 'Illuminates with active race control flag status',
    sound: 'beep',
  },
]
